Repository hiker/fab, pull requests merged in 2024-03, with the labels that each got.

#6 Minor documentation update for #277.
  docs/source/advanced_config.rst
  docs/source/environment.rst
  docs/source/writing_config.rst
  source/fab/steps/compile_fortran.py
Labels: documentation, ready-to-be-merged

#7 278 absolute paths in compilation
  source/fab/steps/compile_fortran.py
Labels: enhancement, ready-to-be-merged

#9 Fix test error - Issue hiker#4, hiker#5
  tests/system_tests/psyclone/skeleton/algorithm/algorithm_mod.x90
  tests/system_tests/psyclone/test_psyclone_system_test.py
  tests/system_tests/svn_fcm/test_svn_fcm_system_test.py
  tests/unit_tests/steps/grab/test_svn_fcm_unit_test.py
  tests/unit_tests/steps/test_psyclone_unit_test.py
Labels: bug, ready-for-review
